project:
  type: website
  output-dir: docs

website:
  title: "R-releases"
  navbar:
    logo: "logo/logo-readme.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - users.qmd
      - contributors.qmd
      - review.qmd
    tools:
      - icon: github
        menu:
          - text: Contribute package
            url:  https://github.com/r-releases/r-releases
          - text: Report bug
            url:  https://github.com/r-releases/help
      - icon: rocket-takeoff
        href: https://r-releases.r-universe.dev/
  body-footer: |
    <br />&copy; 2024 Contributors to the R-releases project.

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
