project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - users.qmd
    - contributors.qmd
    - review.qmd
    - conduct.qmd

website:
  title: "R-releases"
  navbar:
    logo: "logo/logo-readme.png"
    left:
      - about.qmd
      - users.qmd
      - contributors.qmd
      - review.qmd
      - conduct.qmd
    tools:
      - icon: github
        menu:
          - text: Contribute
            url: https://github.com/r-releases/contributions
          - text: Report Issue
            url: https://github.com/r-releases/help
      - icon: rocket-takeoff
        href: https://r-releases.r-universe.dev/
  body-footer: |
    <br />&copy; 2024 the R-releases project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
