project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "R-releases"
  site-url: "https://r-releases.github.io/"
  favicon: "logo/logo-hexbin.png"
  navbar:
    logo: "logo/logo-hexbin.png"
    left:
      - about.qmd
      - users.qmd
      - contributors.qmd
    tools:
      - icon: github
        menu:
          - text: Contribute
            url: https://github.com/r-releases/contributions
          - text: Report Issue
            url: https://github.com/r-releases/help
      - icon: rocket-takeoff
        href: https://r-releases.r-universe.dev/
  page-footer:
    left: 
      - text: "&copy; 2024 the R-releases project."
    center: 
      - review.qmd
      - conduct.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
