project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "R-multiverse"
  description: "A community-curated collection of R package releases, powered by R-universe."
  site-url: "https://r-multiverse.org"
  favicon: "logo/logo-hexbin.png"
  image: "logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "logo/logo-hexbin.png"
    logo-alt: "R-multiverse"
    left:
      - about.qmd
      - users.qmd
      - contributors.qmd
      - team.qmd
      - text: "Policies"
        menu:
          - review.qmd
          - conduct.qmd
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-multiverse/contributions
          - text: Report Issue
            url: https://github.com/r-multiverse/help
      - icon: rocket-takeoff
        aria-label: "R-multiverse Community Universe"
        href: https://r-community.r-universe.dev/
  page-footer:
    center: "&copy; 2024 the R-multiverse project."

format:
  html:
    theme: cosmo
    toc: true
