project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "R-releases"
  description: "A community-curated, maintainer-driven repository of R package releases."
  site-url: "https://r-releases.github.io/"
  favicon: "logo/logo-hexbin.png"
  image: "logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "logo/logo-hexbin.png"
    logo-alt: "R-releases"
    left:
      - about.qmd
      - users.qmd
      - contributors.qmd
      - icon: info-circle
        aria-label: "Info"
        menu:
          - review.qmd
          - conduct.qmd
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-releases/contributions
          - text: Report Issue
            url: https://github.com/r-releases/help
      - icon: rocket-takeoff
        aria-label: "R-releases R Universe"
        href: https://r-releases.r-universe.dev/
  page-footer:
    center: "&copy; 2024 the R-releases project."

format:
  html:
    theme: cosmo
    toc: true
